// Photon Protocol Constants

const PHOTON_COMMANDS = {
    ACKNOWLEDGE: 1,
    CONNECT: 2,
    VERIFY_CONNECT: 3,
    DISCONNECT: 4,
    PING: 5,
    SEND_RELIABLE: 6,
    SEND_UNRELIABLE: 7,
    FRAGMENT: 8,
    SEND_UNRELIABLE_FRAGMENT: 9,
    SEND_RELIABLE_FRAGMENT: 10,
    FETCH_SERVER_TIMESTAMP: 12,
    SEND_NEXT_RELIABLE: 13,
    SEND_FRAGMENT: 14
};

const PHOTON_PEER_STATE = {
    DISCONNECTED: 0,
    CONNECTING: 1,
    CONNECTED: 2,
    CONNECTION_LOST: 3,
    DISCONNECTING: 4
};

const PHOTON_TYPES = {
    NULL: 0x2A,
    DICTIONARY: 0x44,
    STRING_ARRAY: 0x61,
    BYTE: 0x62,
    CUSTOM_DATA: 0x63,
    DOUBLE: 0x64,
    FLOAT: 0x66,
    HASH_TABLE: 0x68,
    INTEGER: 0x69,
    SHORT: 0x6B,
    LONG: 0x6C,
    INT_ARRAY: 0x6E,
    BOOLEAN: 0x6F,
    STRING: 0x73,
    BYTE_ARRAY: 0x78,
    ARRAY: 0x79,
    OBJECT_ARRAY: 0x7A
};

const PHOTON_OPERATIONS = {
    AUTHENTICATE: 230,
    JOIN_ROOM: 226,
    LEAVE_ROOM: 227,
    CHANGE_PROPERTIES: 248,
    GET_ROOMS: 253,
    RAISE_EVENT: 255,
    CREATE_ROOM: 227,
    JOIN_RANDOM_ROOM: 225,
    GET_ROOM_LIST: 220
};

const PHOTON_EVENTS = {
    JOIN: 255,
    LEAVE: 254,
    PROPERTIES_CHANGED: 253,
    MASTER_CLIENT_SWITCHED: 208,
    ROOM_LIST_UPDATE: 230
};

const PHOTON_RETURN_CODES = {
    OK: 0,
    OPERATION_INVALID: -3,
    OPERATION_NOT_ALLOWED_IN_CURRENT_STATE: -4,
    ROOM_NOT_FOUND: 32758,
    ROOM_FULL: 32765,
    ROOM_CLOSED: 32764,
    ALREADY_JOINED: 32760,
    PLUGIN_REPORTED_ERROR: 32757,
    PLUGIN_MISMATCH: 32756,
    JOIN_FAILED_PEER_ALREADY_JOINED: 32755,
    JOIN_FAILED_FOUND_INACTIVE_JOINER: 32754,
    JOIN_FAILED_WITH_REJOIN_NOT_ALLOWED: 32753,
    JOIN_FAILED_DENIED: 32752,
    JOIN_FAILED_FOUND_EXCLUDED_USER_ID: 32751
};

const PHOTON_SIGNATURE = 0xFB17;

module.exports = {
    PHOTON_COMMANDS,
    PHOTON_PEER_STATE,
    PHOTON_TYPES,
    PHOTON_OPERATIONS,
    PHOTON_EVENTS,
    PHOTON_RETURN_CODES,
    PHOTON_SIGNATURE
};